name: Prepare node & bun
description: prepare node and bun

runs:
  using: composite
  steps:
    - name: 🏗 Setup yarn
      uses: threeal/setup-yarn-action@v2.0.0
    - name: 📌 Pin Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
