name: Retrieve dependencies
description: fetch dependencies on NPM

runs:
  using: composite
  steps:
    - name: Cache yarn dependencies
      uses: actions/cache@v4
      with:
        path: |
          .yarn/cache
          .yarn/unplugged
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: 📦 Install dependencies
      shell: bash
      run: yarn install
