name: Deploy on firebase live
description: Deploy on firebase hosting live channel

inputs:
  firebaseServiceAccount:
    description: Firebase service account JSON
    required: true
  projectId:
    description: Firebase project ID
    required: true

outputs:
  url:
    description: Deployment URL
    value: ${{ steps.deploy.outputs.details_url }}

runs:
  using: composite
  steps:
    - uses: FirebaseExtended/action-hosting-deploy@v0
      id: deploy
      with:
        firebaseServiceAccount: ${{ inputs.firebaseServiceAccount }}
        projectId: ${{ inputs.projectId }}
        channelId: live
        firebaseToolsVersion: '13.35.1'
