name: Deploy on firebase
description: Deploy on firebase hosting live channel

outputs:
  url:
    description: Deployment URL
    value: ${{ steps.extractor.outputs.url }}

runs:
  using: composite
  steps:
    - name: 📦 Deploy on firebase
      shell: bash
      run: |
        export NODE_OPTIONS="${NODE_OPTIONS:-} --require=$GITHUB_WORKSPACE/.github/scripts/no-keepalive.cjs"
        npx --no-install firebase deploy --only hosting --project "${EXPO_PUBLIC_FB_PROJECT_ID}" | tee output.txt
    - name: Extract deployed URL
      id: extractor
      shell: bash
      run: cat output.txt | grep "Hosting URL" | awk -F 'https://' '{print "https://" $2}' | awk '{print "url="$1}' >> $GITHUB_OUTPUT
